{
 "title": "Image Processing Dashboard",
 "time": { "from": "2024-01-14T23:14:02.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "language", "query": "scala,cpp,go,julia,elixir" },
   { "name": "window", "query": "10s,1min,2min,5min,10min" },
   { "name": "stage", "query": "format ,resolution,size" }
  ]
 },
 "panels": [
  { "title": "$stage worker metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "stage" },
  {
   "title": "Results produced - $stage worker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "A", "reducer": "sum", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "reduce" }
   ]
  },
  {
   "title": "Measured workers - $stage worker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "alias(groupByNodes(stats.gauges.cadvisor.ip_${language}_${stage}_worker.*.*.memory_usage, 'count'), '${stage}_worker')"
    }
   ]
  },
  {
   "title": "CPU usage - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($A-$B)/10000000000", "type": "math" }
   ]
  },
  {
   "title": "Per node throughput - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.$stage.*.results_produced, 2, 'sum'), 'avg'), '$window'), 'mean')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.$stage.*.results_produced, 2, 'sum'), 'max'), '$window'), 'max')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.$stage.*.results_produced, 2, 'sum'), 'min'), '$window'), 'min')"
    }
   ]
  },
  {
   "title": "Memory usage - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_${stage}_worker.*.*.memory_working_set, 4, 'sum'), 'avg'), '$window'), 'mean')"
    }
   ]
  },
  {
   "title": "Combined throughput - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(aggregate(movingAverage(groupByNode(stats.$stage.*.results_produced, 2, 'sum'), '$window'), 'sum'), 'throughput')"
    }
   ]
  },
  {
   "title": "Network usage - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expression": "($E - $B)/10", "type": "math" },
    { "expression": "($D - $A)/10", "type": "math" }
   ]
  },
  {
   "title": "Coefficient of variation - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$D/$E", "type": "math" }
   ]
  },
  { "title": "Aggregated metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Completion time - Manager",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.manager.completion_time, 'completion_time')"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($A-$B)/10000000000", "type": "math" },
    { "expression": "($D-$E)/10000000000", "type": "math" },
    { "expression": "($G-$H)/10000000000", "type": "math" }
   ]
  },
  {
   "title": "Combined throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.size.*.results_produced, 2, 'sum'), 'sum'), '$window'), 'size_worker')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.resolution.*.results_produced, 2, 'sum'), 'sum'), '$window'), 'resolution_worker')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.format.*.results_produced, 2, 'sum'), 'sum'), '$window'), 'format_worker')"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingWindow(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_size_worker.*.*.memory_working_set, 4, 'sum'), 'avg'), '$window', 'average'), 'size_worker')"
    }
   ]
  },
  {
   "title": "Coefficient of variation - Work time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$G/$H", "type": "math" },
    { "expression": "$J/$K", "type": "math" }
   ]
  },
  {
   "title": "Network usage - received bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expression": "($B-$D)/10", "type": "math" },
    { "expression": "($C-$E)/10", "type": "math" },
    { "expression": "($A-$F)/10", "type": "math" }
   ]
  },
  {
   "title": "Coefficient of variation - Results produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" },
    { "expression": "$E/$D", "type": "math" },
    { "expression": "$H/$G", "type": "math" }
   ]
  },
  {
   "title": "Network usage - transmitted bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expression": "($B-$D)/10", "type": "math" },
    { "expression": "($E-$C)/10", "type": "math" },
    { "expression": "($A-$F)/10", "type": "math" }
   ]
  }
 ]
}