{
 "title": "AES Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "language", "query": "rust,go,zig,scala,julia" }
  ]
 },
 "panels": [
  {
   "title": "Completion time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.aes_${language}.completion_time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($A-$B)/10000000000", "type": "math" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "aggregate(stats.gauges.cadvisor.aes_${language}_app.*.*.memory_working_set, 'sum')"
    }
   ]
  }
 ]
}